baseurl = "https://pitch.shunkakinoki.com/"
title = "Pitch by Shun Kakinoki"
paginate = 30
copyright = "Copyright&copy; Shun Kakinoki"

theme = [
  "after-dark"
]

disableLiveReload = false
enableRobotsTXT = true
sectionPagesMenu = "main"

[markup.goldmark.renderer]
  unsafe = true
[markup.tableOfContents]
  startLevel = 1
  endLevel = 6
[markup.highlight]
  noClasses = false
