[package]
name = "pitch"
version = "0.1.0"
authors = ["Shun Kakinoki <shunkakinoki@gmail.com>"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]
license = "MIT"

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }

[dev-dependencies]
clippy = "*"
rustfmt-nightly = "*"
