base_url = "https://pitch.shunkakinoki.com"
compile_sass = true
description = ""
theme = "after-dark"
title = "pitch"

taxonomies = [
    {name = "id", rss = true},
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "Shun Kakinoki"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
after_dark_title = "Pitch"
analytics = "<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create', 'UA-134813374-14', 'auto');ga('send', 'pageview');</script>"
