name: Build
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
      # - name: Test With Jest
      #   run: |
      #     yarn run test
      - name: Build Reveal Site
        run: |
          yarn run build
