name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Run zola build
        run: |
          curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz
          tar -xzf zola.tar.gz
          ./zola build
        env:
          ZOLA_VERSION: "v0.10.0"
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: Run make
        run: |
          make
      - name: Build Reveal Site
        run: |
          yarn run build
          touch public/.nojekyll
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
